In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
data = pd.read_csv('Train_Data.csv')

In [3]:
data

date    campaign    adgroup     ad  impressions  clicks  cost  \
0     01-08-2020  campaign 1  adgroup 1   ad 1           24       6  0.08   
1     01-08-2020  campaign 1  adgroup 2   ad 1            1       0  0.00   
2     01-08-2020  campaign 1  adgroup 3   ad 1           13       4  0.04   
3     01-08-2020  campaign 1  adgroup 4   ad 1            5       4  0.08   
4     01-08-2020  campaign 1  adgroup 1   ad 2          247     126  1.29   
...          ...         ...        ...    ...          ...     ...   ...   
4566  28-02-2021  campaign 1  adgroup 3  ad 55           19       6  0.07   
4567  28-02-2021  campaign 1  adgroup 4  ad 55            1       0  0.00   
4568  28-02-2021  campaign 1  adgroup 3  ad 56           16       8  0.12   
4569  28-02-2021  campaign 1  adgroup 1  ad 56           37      13  0.23   
4570  28-02-2021  campaign 1  adgroup 1  ad 55           19      10  0.14   

      conversions  revenue  
0               0     0.00  
1               0     0.00  
2               0     0.00  
3               0     0.00  
4               4   925.71  
...           ...      ...  
4566            0     0.00  
4567            0     0.00  
4568            1    93.20  
4569            0     0.00  
4570            0     0.00  

[4571 rows x 9 columns]

In [4]:
from sklearn.preprocessing import LabelEncoder
le1 = LabelEncoder()
le2 = LabelEncoder()
data['campaign_n'] = le1.fit_transform(data['campaign'])
data['adgroup_n'] = le2.fit_transform(data['adgroup'])

In [5]:
data['date'] = pd.to_datetime(data['date'])
data['day'] = data['date'].dt.weekday

In [6]:
data

date    campaign    adgroup     ad  impressions  clicks  cost  \
0    2020-01-08  campaign 1  adgroup 1   ad 1           24       6  0.08   
1    2020-01-08  campaign 1  adgroup 2   ad 1            1       0  0.00   
2    2020-01-08  campaign 1  adgroup 3   ad 1           13       4  0.04   
3    2020-01-08  campaign 1  adgroup 4   ad 1            5       4  0.08   
4    2020-01-08  campaign 1  adgroup 1   ad 2          247     126  1.29   
...         ...         ...        ...    ...          ...     ...   ...   
4566 2021-02-28  campaign 1  adgroup 3  ad 55           19       6  0.07   
4567 2021-02-28  campaign 1  adgroup 4  ad 55            1       0  0.00   
4568 2021-02-28  campaign 1  adgroup 3  ad 56           16       8  0.12   
4569 2021-02-28  campaign 1  adgroup 1  ad 56           37      13  0.23   
4570 2021-02-28  campaign 1  adgroup 1  ad 55           19      10  0.14   

      conversions  revenue  campaign_n  adgroup_n  day  
0               0     0.00           0          0    2  
1               0     0.00           0          1    2  
2               0     0.00           0          2    2  
3               0     0.00           0          3    2  
4               4   925.71           0          0    2  
...           ...      ...         ...        ...  ...  
4566            0     0.00           0          2    6  
4567            0     0.00           0          3    6  
4568            1    93.20           0          2    6  
4569            0     0.00           0          0    6  
4570            0     0.00           0          0    6  

[4571 rows x 12 columns]

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
data.drop(['date','campaign','adgroup','ad'],axis=1,inplace=True)

In [9]:
data

impressions  clicks  cost  conversions  revenue  campaign_n  adgroup_n  \
0              24       6  0.08            0     0.00           0          0   
1               1       0  0.00            0     0.00           0          1   
2              13       4  0.04            0     0.00           0          2   
3               5       4  0.08            0     0.00           0          3   
4             247     126  1.29            4   925.71           0          0   
...           ...     ...   ...          ...      ...         ...        ...   
4566           19       6  0.07            0     0.00           0          2   
4567            1       0  0.00            0     0.00           0          3   
4568           16       8  0.12            1    93.20           0          2   
4569           37      13  0.23            0     0.00           0          0   
4570           19      10  0.14            0     0.00           0          0   

      day  
0       2  
1       2  
2       2  
3       2  
4       2  
...   ...  
4566    6  
4567    6  
4568    6  
4569    6  
4570    6  

[4571 rows x 8 columns]

In [13]:
x,test_x,y,test_y = train_test_split(data.drop('revenue',axis=1),data.revenue,test_size=0.1)

In [14]:
x

impressions  clicks  cost  conversions  campaign_n  adgroup_n  day
3629           49      14  0.57            1           0          0    1
1615            8       3  0.36            0           0          2    5
2732          151      72  0.97            0           0          2    1
3374            1       0  0.00            0           0          1    2
1315           27      12  4.31            2           0          0    4
...           ...     ...   ...          ...         ...        ...  ...
2495            5       4  0.10            0           0          3    6
3122           16      10  0.11            0           0          2    1
1126            7       6  1.00            0           0          3    6
2212            7       4  0.10            0           0          1    0
1529            2       0  0.00            0           0          1    2

[4113 rows x 7 columns]

In [15]:
y

3629    125.60
1615      0.00
2732      0.00
3374      0.00
1315    163.25
         ...  
2495      0.00
3122      0.00
1126      0.00
2212      0.00
1529      0.00
Name: revenue, Length: 4113, dtype: float64

In [16]:
x['revenue'] = y

In [17]:
x

impressions  clicks  cost  conversions  campaign_n  adgroup_n  day  \
3629           49      14  0.57            1           0          0    1   
1615            8       3  0.36            0           0          2    5   
2732          151      72  0.97            0           0          2    1   
3374            1       0  0.00            0           0          1    2   
1315           27      12  4.31            2           0          0    4   
...           ...     ...   ...          ...         ...        ...  ...   
2495            5       4  0.10            0           0          3    6   
3122           16      10  0.11            0           0          2    1   
1126            7       6  1.00            0           0          3    6   
2212            7       4  0.10            0           0          1    0   
1529            2       0  0.00            0           0          1    2   

      revenue  
3629   125.60  
1615     0.00  
2732     0.00  
3374     0.00  
1315   163.25  
...       ...  
2495     0.00  
3122     0.00  
1126     0.00  
2212     0.00  
1529     0.00  

[4113 rows x 8 columns]

In [52]:
test_x.reset_index(inplace = True)

In [55]:
test_x.drop('index',axis=1,inplace=True)
test_x

impressions  clicks   cost  conversions  campaign_n  adgroup_n  day
0             10       6   0.73            0           0          0    4
1            215     118   8.86            4           0          2    4
2              1       0   0.00            0           0          1    3
3              3       3   0.37            0           0          3    3
4             17       7   0.09            0           0          2    6
..           ...     ...    ...          ...         ...        ...  ...
453            3       0   0.00            0           0          3    2
454          678     261   9.37            7           0          0    3
455          762     305  40.03            2           0          0    1
456           19       6   0.07            0           0          2    2
457            5       3   1.83            0           0          3    3

[458 rows x 7 columns]

In [157]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()

In [178]:
from xgboost import XGBRegressor
xg = XGBRegressor()

In [179]:
l = []
for i in test_x.index:
    dat = x[(x['adgroup_n'] == test_x['adgroup_n'][i])]
    x1,x2,y1,y2 = train_test_split(dat.drop('revenue',axis=1),dat.revenue,test_size=0.01)
    xg.fit(x1,y1)
    l.append(xg.predict(np.array([test_x.iloc[i,:]])))
    

In [180]:
l

[array([0.96429485], dtype=float32),
 array([342.02072], dtype=float32),
 array([6.782113e-06], dtype=float32),
 array([-0.00238866], dtype=float32),
 array([-0.19091566], dtype=float32),
 array([466.2076], dtype=float32),
 array([0.44226733], dtype=float32),
 array([0.00114665], dtype=float32),
 array([0.0003038], dtype=float32),
 array([3058.79], dtype=float32),
 array([-1.2375422], dtype=float32),
 array([7.939278e-05], dtype=float32),
 array([123.84477], dtype=float32),
 array([179.84645], dtype=float32),
 array([209.59247], dtype=float32),
 array([0.20434065], dtype=float32),
 array([0.19784188], dtype=float32),
 array([-0.01464199], dtype=float32),
 array([-0.00024205], dtype=float32),
 array([368.3342], dtype=float32),
 array([632.1808], dtype=float32),
 array([12.066114], dtype=float32),
 array([117.572365], dtype=float32),
 array([-0.70473045], dtype=float32),
 array([-0.40323833], dtype=float32),
 array([275.48935], dtype=float32),
 array([300.3893], dtype=float32),
 array([1

In [181]:
pred = pd.Series(l)

In [182]:
m = 0
for i in pred:
    pred[m] = i[0]
    m+=1

In [183]:
pred

0         0.964295
1       342.020721
2         0.000007
3        -0.002389
4        -0.190916
          ...     
453      -0.000291
454    1178.117188
455     287.366638
456       0.862358
457       3.703456
Length: 458, dtype: object

In [184]:
from sklearn.metrics import mean_squared_error

In [185]:

rmse = np.sqrt(mean_squared_error(test_y,pred))
rmse

460.226770470993

In [177]:
test_y

1864      0.00
1112    776.82
806       0.00
930       0.00
3358      0.00
         ...  
2536      0.00
2398    952.68
1512    271.60
66        0.00
1418      0.00
Name: revenue, Length: 458, dtype: float64

In [188]:
x1

impressions  clicks  cost  conversions  campaign_n  adgroup_n  day
3613            7       2  0.05            0           0          3    1
1126            7       6  1.00            0           0          3    6
3726            7       5  0.06            0           0          3    5
4050            1       0  0.00            0           0          3    6
1648            5       3  0.69            0           0          3    5
...           ...     ...   ...          ...         ...        ...  ...
670            11       9  0.39            0           0          3    6
1424           22      10  2.44            0           0          3    3
2775            6       3  0.04            0           0          3    3
2345            6       3  0.25            0           0          3    6
3903            1       1  0.01            0           0          3    5

[753 rows x 7 columns]

In [189]:
y1

3613    0.0
1126    0.0
3726    0.0
4050    0.0
1648    0.0
       ... 
670     0.0
1424    0.0
2775    0.0
2345    0.0
3903    0.0
Name: revenue, Length: 753, dtype: float64

In [191]:
pd.set_option('display.max_rows', 5000)
data_2 = pd.read_csv('Train_Data.csv')
data_2

date    campaign    adgroup     ad  impressions  clicks    cost  \
0     01-08-2020  campaign 1  adgroup 1   ad 1           24       6    0.08   
1     01-08-2020  campaign 1  adgroup 2   ad 1            1       0    0.00   
2     01-08-2020  campaign 1  adgroup 3   ad 1           13       4    0.04   
3     01-08-2020  campaign 1  adgroup 4   ad 1            5       4    0.08   
4     01-08-2020  campaign 1  adgroup 1   ad 2          247     126    1.29   
5     01-08-2020  campaign 1  adgroup 2   ad 2            7       2    0.04   
6     01-08-2020  campaign 1  adgroup 4   ad 2            6       3    0.05   
7     01-08-2020  campaign 1  adgroup 1   ad 3          129      52    0.58   
8     01-08-2020  campaign 1  adgroup 3   ad 3          104      56    0.56   
9     01-08-2020  campaign 1  adgroup 4   ad 3            6       5    0.05   
10    01-08-2020  campaign 1  adgroup 2   ad 3            4       0    0.00   
11    01-08-2020  campaign 1  adgroup 3   ad 4           39      16    0.22   
12    01-08-2020  campaign 1  adgroup 3   ad 5           17       6    0.06   
13    01-08-2020  campaign 1  adgroup 3   ad 6          253     128    1.32   
14    01-08-2020  campaign 1  adgroup 3   ad 7           16       6    0.07   
15    01-08-2020  campaign 1  adgroup 1   ad 7           26      10    0.10   
16    01-08-2020  campaign 1  adgroup 2   ad 7            5       2    0.04   
17    01-08-2020  campaign 1  adgroup 3   ad 8          250     114    1.17   
18    01-08-2020  campaign 1  adgroup 3   ad 9          261     123    1.27   
19    01-08-2020  campaign 1  adgroup 2   ad 9            5       0    0.00   
20    01-08-2020  campaign 1  adgroup 1   ad 9          329     130    1.40   
21    01-08-2020  campaign 1  adgroup 4   ad 9            2       2    0.02   
22    01-08-2020  campaign 1  adgroup 1  ad 10            5       2    0.02   
23    02-08-2020  campaign 1  adgroup 1   ad 1           21       8    0.09   
24    02-08-2020  campaign 1  adgroup 3   ad 1           21      16    0.18   
25    02-08-2020  campaign 1  adgroup 4   ad 1            6       2    0.02   
26    02-08-2020  campaign 1  adgroup 1   ad 2          197     112    1.18   
27    02-08-2020  campaign 1  adgroup 4   ad 2           11       5    0.05   
28    02-08-2020  campaign 1  adgroup 2   ad 2            4       1    0.01   
29    02-08-2020  campaign 1  adgroup 3   ad 3          129      68    0.69   
30    02-08-2020  campaign 1  adgroup 4   ad 3            4       4    0.05   
31    02-08-2020  campaign 1  adgroup 1   ad 3          105      40    0.46   
32    02-08-2020  campaign 1  adgroup 2   ad 3            2       0    0.00   
33    02-08-2020  campaign 1  adgroup 3   ad 4           62      40    0.44   
34    02-08-2020  campaign 1  adgroup 3   ad 5           10       8    0.08   
35    02-08-2020  campaign 1  adgroup 3   ad 6          258     139    1.43   
36    02-08-2020  campaign 1  adgroup 3   ad 7           17       9    0.10   
37    02-08-2020  campaign 1  adgroup 1   ad 7           31      14    0.15   
38    02-08-2020  campaign 1  adgroup 3   ad 8          243     117    1.21   
39    02-08-2020  campaign 1  adgroup 4   ad 9            5       1    0.01   
40    02-08-2020  campaign 1  adgroup 1   ad 9          212      79    0.86   
41    02-08-2020  campaign 1  adgroup 2   ad 9            3       2    0.02   
42    02-08-2020  campaign 1  adgroup 3   ad 9          245     140    1.44   
43    02-08-2020  campaign 1  adgroup 1  ad 10           12       4    0.04   
44    03-08-2020  campaign 1  adgroup 4   ad 1            2       1    0.01   
45    03-08-2020  campaign 1  adgroup 1   ad 1           49      13    0.13   
46    03-08-2020  campaign 1  adgroup 3   ad 1            7       7    0.07   
47    03-08-2020  campaign 1  adgroup 1   ad 2          304     156    1.75   
48    03-08-2020  campaign 1  adgroup 2   ad 2            7       0    0.00   
49    03-08-2020  campaign 1  adgroup 4   ad 2            9   

In [204]:
data_2[(data_2['ad'] == 'ad 7') & (data_2['adgroup'] == 'adgroup 1')]

date    campaign    adgroup    ad  impressions  clicks  cost  \
15    01-08-2020  campaign 1  adgroup 1  ad 7           26      10  0.10   
37    02-08-2020  campaign 1  adgroup 1  ad 7           31      14  0.15   
58    03-08-2020  campaign 1  adgroup 1  ad 7           22       8  0.08   
79    04-08-2020  campaign 1  adgroup 1  ad 7           25      11  0.12   
100   05-08-2020  campaign 1  adgroup 1  ad 7           34      15  0.16   
118   06-08-2020  campaign 1  adgroup 1  ad 7           52      28  0.32   
137   07-08-2020  campaign 1  adgroup 1  ad 7           48      23  0.26   
155   08-08-2020  campaign 1  adgroup 1  ad 7           21      10  0.12   
173   09-08-2020  campaign 1  adgroup 1  ad 7           71      35  0.37   
191   10-08-2020  campaign 1  adgroup 1  ad 7           75      34  0.40   
212   11-08-2020  campaign 1  adgroup 1  ad 7           70      33  0.34   
229   12-08-2020  campaign 1  adgroup 1  ad 7           69      23  0.26   
246   13-08-2020  campaign 1  adgroup 1  ad 7           59      24  0.26   
265   14-08-2020  campaign 1  adgroup 1  ad 7           69      29  0.33   
282   15-08-2020  campaign 1  adgroup 1  ad 7           42      15  0.15   
298   16-08-2020  campaign 1  adgroup 1  ad 7           51      18  0.20   
316   17-08-2020  campaign 1  adgroup 1  ad 7           82      33  0.38   
335   18-08-2020  campaign 1  adgroup 1  ad 7           68      26  0.32   
350   19-08-2020  campaign 1  adgroup 1  ad 7           99      42  0.51   
366   20-08-2020  campaign 1  adgroup 1  ad 7           46      20  0.22   
384   21-08-2020  campaign 1  adgroup 1  ad 7           96      48  0.51   
399   22-08-2020  campaign 1  adgroup 1  ad 7           56      29  0.36   
418   23-08-2020  campaign 1  adgroup 1  ad 7           93      39  0.47   
435   24-08-2020  campaign 1  adgroup 1  ad 7          115      55  0.63   
454   25-08-2020  campaign 1  adgroup 1  ad 7           16      10  0.12   
551   01-09-2020  campaign 1  adgroup 1  ad 7           26      14  0.95   
568   02-09-2020  campaign 1  adgroup 1  ad 7          224     128  4.16   
587   03-09-2020  campaign 1  adgroup 1  ad 7          248     137  6.20   
607   04-09-2020  campaign 1  adgroup 1  ad 7          198     112  4.96   
625   05-09-2020  campaign 1  adgroup 1  ad 7          170      80  3.88   
640   06-09-2020  campaign 1  adgroup 1  ad 7           28      18  0.65   
754   14-09-2020  campaign 1  adgroup 1  ad 7           17       9  0.11   
774   15-09-2020  campaign 1  adgroup 1  ad 7            9       5  0.05   
792   16-09-2020  campaign 1  adgroup 1  ad 7           10       7  0.07   
813   17-09-2020  campaign 1  adgroup 1  ad 7            9       2  0.02   
832   18-09-2020  campaign 1  adgroup 1  ad 7            5       1  0.01   
850   19-09-2020  campaign 1  adgroup 1  ad 7            4       2  0.02   
867   20-09-2020  campaign 1  adgroup 1  ad 7           11       7  0.08   
887   21-09-2020  campaign 1  adgroup 1  ad 7           10       8  0.10   
902   22-09-2020  campaign 1  adgroup 1  ad 7           18      11  0.11   
922   23-09-2020  campaign 1  adgroup 1  ad 7           13       9  0.10   
941   24-09-2020  campaign 1  adgroup 1  ad 7           13       6  0.06   
961   25-09-2020  campaign 1  adgroup 1  ad 7           13       4  0.14   
979   26-09-2020  campaign 1  adgroup 1  ad 7           10       5  0.11   
997   27-09-2020  campaign 1  adgroup 1  ad 7           17       8  0.20   
1020  28-09-2020  campaign 1  adgroup 1  ad 7            2       0  0.00   
1057  01-10-2020  campaign 1  adgroup 1  ad 7            9       6  0.34   
1072  02-10-2020  campaign 1  adgroup 1  ad 7           14       5  0.35   
1089  03-10-2020  campaign 1  adgroup 1  ad 7            8       4  0.39   
1110  04-10-2020  campaign 1  adgroup 1  ad 7            7       5  0.16   
1221  11-10-2020  campaign 1  adgroup 1  ad 7           27       7  4.02   
1240  12-10-2020  campaign 1  adgroup 1  ad 7            9  

In [202]:
test_data = pd.read_csv('Test_Data.csv')
test_data.campaign.value_counts()

campaign 1    318
Name: campaign, dtype: int64